/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment;

public class App {
    public static void main(String[] args){

        //Vert.x implementation of assignment
        //JavaParserVertxFrame frame = new JavaParserVertxFrame();

        //RXJava implementation of assignment
        JavaParserRxImpl javaParserRx = new JavaParserRxImpl();
        JavaParserRxFrame frame = new JavaParserRxFrame(javaParserRx);

        //javaParserRx.getClassReport("prova.txt");
    }
}
