/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment;

public class App {
    public static void main(String[] args){
        
        String path = "";
        ClassReport classReport = new ClassReport(path);
        classReport.getReport();
        InterfaceReport interfaceReport = new InterfaceReport(path);
        interfaceReport.getReport();
        PackageReport packageReport = new PackageReport(path);
        packageReport.getReport();
        ProjectReport projectReport = new ProjectReport(path);
        projectReport.getReport();
    }
}
